name: Test Python Solutions

on:
  push:
    paths:
      - "solutions/**/*.py"
      - "runners/**/*.py"
      - "tests/**/*.json"
  pull_request:
    paths:
      - "solutions/**/*.py"
      - "runners/**/*.py"
      - "tests/**/*.json"
  workflow_dispatch:

jobs:
  test-py-solutions:
    name: Run Python Test Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Make runner executable
        run: chmod +x runners/run_tests_py.py

      - name: Run Tests for Changed Python Files
        run: |
          CHANGED_PY=$(git diff --name-only HEAD~1 | grep '\.py$' || true)

          if [ -z "$CHANGED_PY" ]; then
            echo "📭 No changed Python files. Skipping tests."
            exit 0
          fi

          for file in $CHANGED_PY; do
            if [[ "$file" == solutions/*/*.py ]]; then
              sol="$file"

              # ✅ Skip if file was deleted
              if [ ! -f "$sol" ]; then
                echo "🗑️  Skipping deleted file $sol"
                continue
              fi

              daydir=$(dirname "$sol")
              day=$(basename "$daydir")
              day_cleaned=$(echo "$day" | tr -d '-')  # remove dashes like day-01 → day01
              testfile="tests/$day_cleaned.json"

              if [ -f "$testfile" ]; then
                echo "🧪 Testing $sol with $testfile"
                python runners/run_tests_py.py "$testfile" "$sol"
              else
                echo "⚠️ Skipping $sol: No matching test file at $testfile"
              fi
            fi
          done 